<a href="https://colab.research.google.com/github/ntomben97/NYC-Yellow-Taxi-Big-Data-Project/blob/main/Cleaning__Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pyspark installation

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!pip install pyspark -q

Mounted at /content/drive

Creating Spark Session

In [ ]:
from pyspark.sql import SparkSession
from pathlib import Path
import pandas as pd
from pyspark.sql import functions as F

spark = SparkSession.builder \
    .appName("NYC Taxi Analysis") \
    .getOrCreate()

Loading Data

In [ ]:
DATA_PATH = "/content/drive/MyDrive/MIT805/Group Project/src"

df = spark.read.parquet(f"{DATA_PATH}/*.parquet")

df.show(5)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+
|       2| 2014-01-01 00:02:00|  2014-01-01 00:04:00|              6|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.02|         0.0|                  0.0|        4.52|                NULL|       NULL|
|       2| 2014-01-01 00:06:00|  2014-01-01 00:09:00|              5|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.05|         0.0|                  0.0|        4.55|                NULL|       NULL|
|       2| 2014-01-01 00:10:00|  2014-01-01 00:13:00|              5|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.08|         0.0|                  0.0|        4.58|                NULL|       NULL|
|       2| 2014-01-01 00:54:00|  2014-01-01 00:55:00|              5|          0.0|         1|              NULL|         264|         264|           2|        2.5|  0.5|    0.5|       0.0|         0.0|                  0.0|         3.5|                NULL|       NULL|
|       1| 2014-01-01 00:29:18|  2014-01-01 00:35:13|              2|          1.8|         1|                 N|         229|         262|           2|        7.5|  0.5|    0.5|       0.0|         0.0|                  0.0|         8.5|                NULL|       NULL|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+
only showing top 5 rows

In [ ]:
total_rows = df.count()
print(f"Total rows: {total_rows:,}")
print(f"Total columns: {len(df.columns)}")

Total rows: 986,000,101
Total columns: 19

Column Name Discepancies

Using the Latest file as reference

In [ ]:
files = sorted(Path(DATA_PATH).glob("*.parquet"))

print(f"Number of files: {len(files)}")

reference_file = Path(DATA_PATH) / "yellow_tripdata_2026-05.parquet"

reference_df = spark.read.parquet(str(reference_file))

print("Reference file:")
print(reference_file.name)

reference_df.printSchema()

Number of files: 149
Reference file:
yellow_tripdata_2026-05.parquet
root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)

In [ ]:
reference_schema = {
    field.name.lower(): field.dataType.simpleString()
    for field in reference_df.schema.fields
}

print(reference_schema)

{'vendorid': 'int', 'tpep_pickup_datetime': 'timestamp_ntz', 'tpep_dropoff_datetime': 'timestamp_ntz', 'passenger_count': 'bigint', 'trip_distance': 'double', 'ratecodeid': 'bigint', 'store_and_fwd_flag': 'string', 'pulocationid': 'int', 'dolocationid': 'int', 'payment_type': 'bigint', 'fare_amount': 'double', 'extra': 'double', 'mta_tax': 'double', 'tip_amount': 'double', 'tolls_amount': 'double', 'improvement_surcharge': 'double', 'total_amount': 'double', 'congestion_surcharge': 'double', 'airport_fee': 'double', 'cbd_congestion_fee': 'double'}

In [ ]:
schema_differences = []

for file in files:

    current_df = spark.read.parquet(str(file))

    current_schema = {
      field.name.lower(): field.dataType.simpleString()
      for field in current_df.schema.fields
  }

    all_columns = set(reference_schema) | set(current_schema)

    for column in sorted(all_columns):

        reference_type = reference_schema.get(column, "MISSING")
        current_type = current_schema.get(column, "MISSING")

        if reference_type != current_type:

            schema_differences.append({
                "file": file.name,
                "column": column,
                "reference_type": reference_type,
                "actual_type": current_type
            })

In [ ]:
differences_pd = pd.DataFrame(schema_differences)

differences_pd

,file,column,reference_type,actual_type
0,yellow_tripdata_2014-01.parquet,airport_fee,double,int
1,yellow_tripdata_2014-01.parquet,cbd_congestion_fee,double,MISSING
2,yellow_tripdata_2014-01.parquet,dolocationid,int,bigint
3,yellow_tripdata_2014-01.parquet,pulocationid,int,bigint
4,yellow_tripdata_2014-01.parquet,vendorid,int,bigint
...,...,...,...,...
699,yellow_tripdata_2024-08.parquet,cbd_congestion_fee,double,MISSING
700,yellow_tripdata_2024-09.parquet,cbd_congestion_fee,double,MISSING
701,yellow_tripdata_2024-10.parquet,cbd_congestion_fee,double,MISSING
702,yellow_tripdata_2024-11.parquet,cbd_congestion_fee,double,MISSING
703,yellow_tripdata_2024-12.parquet,cbd_congestion_fee,double,MISSING

In [ ]:
differences_pd.groupby(
    ["column", "reference_type", "actual_type"]
).size().reset_index(name="number_of_files").sort_values(
    "number_of_files",
    ascending=False
)

                  column reference_type actual_type  number_of_files
1     cbd_congestion_fee         double     MISSING              132
8               vendorid            int      bigint              109
3           dolocationid            int      bigint              109
6           pulocationid            int      bigint              109
0            airport_fee         double         int               79
5        passenger_count         bigint      double               55
2   congestion_surcharge         double         int               55
7             ratecodeid         bigint      double               55
4  improvement_surcharge         double         int                1

In [ ]:
target_types = {
    "vendorid": "bigint",
    "pulocationid": "bigint",
    "dolocationid": "bigint",
    "airport_fee": "double",
    "passenger_count": "double",
    "congestion_surcharge": "double",
    "ratecodeid": "bigint",
    "improvement_surcharge": "double",
    "cbd_congestion_fee": "double"
}

In [ ]:
standardised_dfs = []

for file in files:

    temp_df = spark.read.parquet(str(file))

    # Make column names lowercase
    for column in temp_df.columns:
        temp_df = temp_df.withColumnRenamed(
            column,
            column.lower()
        )

    # Standardise the required columns
    for column, target_type in target_types.items():

        if column in temp_df.columns:

            temp_df = temp_df.withColumn(
                column,
                F.col(column).cast(target_type)
            )

        else:

            # Column did not exist in this historical file
            temp_df = temp_df.withColumn(
                column,
                F.lit(None).cast(target_type)
            )

    standardised_dfs.append(temp_df)

In [ ]:
df_standardised = standardised_dfs[0]

for temp_df in standardised_dfs[1:]:
    df_standardised = df_standardised.unionByName(
        temp_df,
        allowMissingColumns=True
    )

df_standardised.show(5)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
|vendorid|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|ratecodeid|store_and_fwd_flag|pulocationid|dolocationid|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
|       2| 2014-01-01 00:02:00|  2014-01-01 00:04:00|            6.0|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.02|         0.0|                  0.0|        4.52|                NULL|       NULL|              NULL|
|       2| 2014-01-01 00:06:00|  2014-01-01 00:09:00|            5.0|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.05|         0.0|                  0.0|        4.55|                NULL|       NULL|              NULL|
|       2| 2014-01-01 00:10:00|  2014-01-01 00:13:00|            5.0|          0.0|         1|              NULL|         146|         146|           1|        3.5|  0.5|    0.5|      0.08|         0.0|                  0.0|        4.58|                NULL|       NULL|              NULL|
|       2| 2014-01-01 00:54:00|  2014-01-01 00:55:00|            5.0|          0.0|         1|              NULL|         264|         264|           2|        2.5|  0.5|    0.5|       0.0|         0.0|                  0.0|         3.5|                NULL|       NULL|              NULL|
|       1| 2014-01-01 00:29:18|  2014-01-01 00:35:13|            2.0|          1.8|         1|                 N|         229|         262|           2|        7.5|  0.5|    0.5|       0.0|         0.0|                  0.0|         8.5|                NULL|       NULL|              NULL|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
only showing top 5 rows

In [ ]:
df_standardised.printSchema()

root
 |-- vendorid: long (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: double (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- ratecodeid: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- pulocationid: long (nullable = true)
 |-- dolocationid: long (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)

Dealing with Null Values

In [ ]:
total_rows = df_standardised.count()

null_results = []

for column in df_standardised.columns:

    print(f"Checking: {column}")

    null_count = (
        df_standardised
        .select(
            F.sum(
                F.when(F.col(column).isNull(), 1)
                .otherwise(0)
            ).alias("null_count")
        )
        .collect()[0]["null_count"]
    )

    null_results.append({
        "Column": column,
        "Null_Count": null_count,
        "Null_Percentage": (null_count / total_rows) * 100
    })

    print(
        f"  Nulls: {null_count:,} "
        f"({(null_count / total_rows) * 100:.2f}%)"
    )

Checking: vendorid
  Nulls: 0 (0.00%)
Checking: tpep_pickup_datetime
  Nulls: 0 (0.00%)
Checking: tpep_dropoff_datetime
  Nulls: 0 (0.00%)
Checking: passenger_count
  Nulls: 25,984,554 (2.64%)
Checking: trip_distance
  Nulls: 0 (0.00%)
Checking: ratecodeid
  Nulls: 25,984,554 (2.64%)
Checking: store_and_fwd_flag
  Nulls: 76,104,792 (7.72%)
Checking: pulocationid
  Nulls: 0 (0.00%)
Checking: dolocationid
  Nulls: 0 (0.00%)
Checking: payment_type
  Nulls: 0 (0.00%)
Checking: fare_amount
  Nulls: 0 (0.00%)
Checking: extra
  Nulls: 0 (0.00%)
Checking: mta_tax
  Nulls: 0 (0.00%)
Checking: tip_amount
  Nulls: 0 (0.00%)
Checking: tolls_amount
  Nulls: 0 (0.00%)
Checking: improvement_surcharge
  Nulls: 53,750,503 (5.45%)
Checking: total_amount
  Nulls: 0 (0.00%)
Checking: congestion_surcharge
  Nulls: 689,772,615 (69.96%)
Checking: airport_fee
  Nulls: 797,072,315 (80.84%)
Checking: cbd_congestion_fee
  Nulls: 918,278,217 (93.13%)

In [ ]:
# ============================================================
# 1. Find the most common passenger_count
# ============================================================

passenger_mode = (
    df_standardised
    .filter(F.col("passenger_count").isNotNull())
    .groupBy("passenger_count")
    .count()
    .orderBy(F.desc("count"))
    .first()["passenger_count"]
)

print(f"Passenger count mode: {passenger_mode}")


# ============================================================
# 2. Replace NULL values
# ============================================================

df_cleaned = (
    df_standardised

    # Passenger count → mode
    .withColumn(
        "passenger_count",
        F.coalesce(
            F.col("passenger_count"),
            F.lit(float(passenger_mode))
        )
    )

    # Rate code → 99 = Unknown
    .withColumn(
        "ratecodeid",
        F.coalesce(
            F.col("ratecodeid"),
            F.lit(99).cast("bigint")
        )
    )

    # Store and forward flag → Unknown
    .withColumn(
        "store_and_fwd_flag",
        F.coalesce(
            F.col("store_and_fwd_flag"),
            F.lit("Unknown")
        )
    )

    # Improvement surcharge → 0
    .withColumn(
        "improvement_surcharge",
        F.coalesce(
            F.col("improvement_surcharge"),
            F.lit(0.0)
        )
    )

    # Congestion surcharge → 0
    .withColumn(
        "congestion_surcharge",
        F.coalesce(
            F.col("congestion_surcharge"),
            F.lit(0.0)
        )
    )

    # Airport fee → 0
    .withColumn(
        "airport_fee",
        F.coalesce(
            F.col("airport_fee"),
            F.lit(0.0)
        )
    )

    # CBD congestion fee → 0
    .withColumn(
        "cbd_congestion_fee",
        F.coalesce(
            F.col("cbd_congestion_fee"),
            F.lit(0.0)
        )
    )
)

Passenger count mode: 1.0

In [ ]:
cleaned_columns = [
    "passenger_count",
    "ratecodeid",
    "store_and_fwd_flag",
    "improvement_surcharge",
    "congestion_surcharge",
    "airport_fee",
    "cbd_congestion_fee"
]

null_check = df_cleaned.select([
    F.sum(
        F.when(F.col(c).isNull(), 1).otherwise(0)
    ).alias(c)
    for c in cleaned_columns
])

null_check.show(vertical=True)

-RECORD 0--------------------
 passenger_count       | 0
 ratecodeid            | 0
 store_and_fwd_flag    | 0
 improvement_surcharge | 0
 congestion_surcharge  | 0
 airport_fee           | 0
 cbd_congestion_fee    | 0

In [ ]:
df = df_cleaned

# ============================================================
# 1. DEFINE VALIDATION CONDITIONS
# ============================================================

checks = {

    # VendorID must be 1, 2, 6 or 7
    "VendorID": ~F.col("VendorID").isin(1, 2, 6, 7),

    # Pickup date: January 2014 through May 2025
    "tpep_pickup_datetime": (
        (F.col("tpep_pickup_datetime") < F.lit("2014-01-01")) |
        (F.col("tpep_pickup_datetime") >= F.lit("2025-06-01"))
    ),

    # Dropoff date: January 2014 through May 2025
    "tpep_dropoff_datetime": (
        (F.col("tpep_dropoff_datetime") < F.lit("2014-01-01")) |
        (F.col("tpep_dropoff_datetime") >= F.lit("2025-06-01"))
    ),

    # Passenger count must not be negative
    "passenger_count": F.col("passenger_count") < 0,

    # Trip distance must not be negative
    "trip_distance": F.col("trip_distance") < 0,

    # Store and forward flag must be Y, N or UNKNOWN
    "store_and_fwd_flag": (
        ~F.upper(F.col("store_and_fwd_flag")).isin("Y", "N", "UNKNOWN")
    ),

    # Payment type must be between 0 and 6
    "payment_type": (
        (F.col("payment_type") < 0) |
        (F.col("payment_type") > 6)
    )
}


# ============================================================
# 2. AMOUNT COLUMNS
# ============================================================

amount_columns = [
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee"
]

# Only use amount columns that exist
amount_columns = [
    c for c in amount_columns
    if c in df.columns
]

for column in amount_columns:
    checks[column] = F.col(column) < 0


# ============================================================
# 3. COUNT INVALID VALUES
# ============================================================

total_rows = df.count()

results = []

for column_name, condition in checks.items():

    invalid_count = df.filter(condition).count()

    valid_count = total_rows - invalid_count

    invalid_percentage = (
        (invalid_count / total_rows) * 100
        if total_rows > 0 else 0
    )

    results.append((
        column_name,
        total_rows,
        valid_count,
        invalid_count,
        invalid_percentage
    ))


# ============================================================
# 4. CREATE VALIDATION REPORT
# ============================================================

validation_report = spark.createDataFrame(
    results,
    [
        "Column",
        "Total_Rows",
        "Valid_Rows",
        "Invalid_Rows",
        "Invalid_Percentage"
    ]
)

validation_report.orderBy(
    F.desc("Invalid_Rows")
).show(
    len(results),
    truncate=False
)

+---------------------+----------+----------+------------+---------------------+
|Column               |Total_Rows|Valid_Rows|Invalid_Rows|Invalid_Percentage   |
+---------------------+----------+----------+------------+---------------------+
|tpep_dropoff_datetime|986000101 |938033133 |47966968    |4.8648035584734695   |
|tpep_pickup_datetime |986000101 |938035958 |47964143    |4.864517047346631    |
|fare_amount          |986000101 |981018827 |4981274     |0.5052001510900453   |
|total_amount         |986000101 |983014300 |2985801     |0.30281954301747077  |
|improvement_surcharge|986000101 |983223251 |2776850     |0.28162776019837343  |
|mta_tax              |986000101 |983296504 |2703597     |0.27419845061456033  |
|congestion_surcharge |986000101 |983961525 |2038576     |0.20675210863898277  |
|extra                |986000101 |984606584 |1393517     |0.14133031006657068  |
|VendorID             |986000101 |985229844 |770257      |0.0781193631946697   |
|airport_fee          |986000101 |985624115 |375986      |0.038132450454992396 |
|tolls_amount         |986000101 |985821241 |178860      |0.018139957573898868 |
|tip_amount           |986000101 |985982158 |17943       |0.0018197766898606026|
|trip_distance        |986000101 |985988657 |11444       |0.0011606489683310894|
|passenger_count      |986000101 |986000101 |0           |0.0                  |
|store_and_fwd_flag   |986000101 |986000101 |0           |0.0                  |
|payment_type         |986000101 |986000101 |0           |0.0                  |
+---------------------+----------+----------+------------+---------------------+

In [ ]:

validation_conditions = {
    "RatecodeID": ~F.col("RatecodeID").isin(1, 2, 3, 4, 5, 6, 99),
    "PULocationID": F.col("PULocationID") < 0,
    "DOLocationID": F.col("DOLocationID") < 0
}

results = []

for column_name, condition in validation_conditions.items():

    invalid_count = (
        df_cleaned
        .filter(condition)
        .count()
    )

    invalid_percentage = (invalid_count / total_rows) * 100

    results.append((
        column_name,
        total_rows,
        invalid_count,
        invalid_percentage
    ))

validation_df = spark.createDataFrame(
    results,
    ["Column", "Total_Rows", "Invalid_Rows", "Invalid_Percentage"]
)

validation_df.show(truncate=False)

+------------+----------+------------+------------------+
|Column      |Total_Rows|Invalid_Rows|Invalid_Percentage|
+------------+----------+------------+------------------+
|RatecodeID  |986000101 |0           |0.0               |
|PULocationID|986000101 |0           |0.0               |
|DOLocationID|986000101 |0           |0.0               |
+------------+----------+------------+------------------+

Looking into tpep_dropoff_datetime and tpep_pickup_datetime

In [ ]:
file_path = "/content/drive/MyDrive/MIT805/Group Project/src/yellow_tripdata_2022-06.parquet"

df_2022_06 = spark.read.parquet(file_path)

df_2022_06.filter(
    F.col("tpep_pickup_datetime") < F.lit("2014-01-01")
).select(
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "vendorid",
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "total_amount"
).show(50, truncate=False)

+--------------------+---------------------+--------+---------------+-------------+-----------+------------+
|tpep_pickup_datetime|tpep_dropoff_datetime|vendorid|passenger_count|trip_distance|fare_amount|total_amount|
+--------------------+---------------------+--------+---------------+-------------+-----------+------------+
|2001-08-23 05:34:45 |2001-08-23 05:57:11  |2       |1.0            |7.08         |22.5       |24.55       |
|2002-10-21 00:13:16 |2002-10-21 00:24:37  |2       |1.0            |2.78         |11.0       |17.76       |
|2002-10-21 00:25:44 |2022-06-06 00:40:18  |2       |1.0            |3.01         |13.0       |20.16       |
|2002-10-21 00:27:54 |2002-10-21 00:44:31  |2       |2.0            |3.27         |13.5       |17.3        |
|2002-10-21 00:50:00 |2002-10-21 00:50:06  |2       |3.0            |0.0          |66.0       |66.3        |
|2002-10-21 01:38:48 |2022-06-06 01:49:22  |2       |1.0            |4.29         |14.5       |20.8        |
|2002-10-21 05:50:56 |2002-10-21 05:53:32  |2       |1.0            |0.6          |4.0        |7.8         |
|2002-10-21 05:54:54 |2002-10-21 06:09:23  |2       |1.0            |4.84         |16.5       |20.3        |
|2002-10-21 08:06:54 |2002-10-21 08:29:19  |2       |1.0            |3.33         |16.0       |19.3        |
|2002-10-21 08:31:53 |2002-10-21 08:40:48  |2       |1.0            |1.55         |8.0        |11.3        |
|2002-10-21 09:07:51 |2002-10-21 09:30:09  |2       |1.0            |2.86         |15.5       |18.8        |
|2002-10-21 09:55:45 |2002-10-21 10:13:59  |2       |1.0            |5.6          |19.5       |20.3        |
|2002-10-21 09:52:38 |2002-10-21 09:58:34  |2       |1.0            |1.01         |5.5        |6.3         |
|2002-10-21 09:59:19 |2022-06-06 10:24:57  |2       |1.0            |7.78         |25.5       |28.8        |
|2002-10-21 09:50:44 |2002-10-21 10:17:17  |2       |1.0            |8.89         |27.0       |39.35       |
|2002-10-21 10:36:45 |2002-10-21 11:08:24  |2       |1.0            |7.83         |28.0       |33.8        |
|2002-10-21 10:05:56 |2022-06-06 10:44:30  |2       |2.0            |14.12        |43.5       |53.35       |
|2002-10-21 10:06:22 |2022-06-06 10:27:42  |2       |1.0            |2.83         |-15.0      |-18.3       |
|2002-10-21 10:06:22 |2022-06-06 10:27:42  |2       |1.0            |2.83         |15.0       |18.3        |
|2002-10-21 10:18:52 |2002-10-21 10:26:55  |2       |1.0            |0.92         |7.0        |9.36        |
|2002-10-21 11:21:37 |2002-10-21 11:29:57  |2       |2.0            |0.87         |6.5        |7.3         |
|2002-10-21 11:35:50 |2022-06-06 11:58:56  |2       |1.0            |1.84         |14.5       |21.36       |
|2002-10-21 11:55:31 |2022-06-06 12:19:43  |2       |1.0            |2.93         |16.5       |19.8        |
|2002-10-21 11:21:19 |2022-06-06 11:48:36  |2       |3.0            |8.71         |28.0       |45.42       |
|2002-10-21 12:05:23 |2002-10-21 12:17:27  |2       |1.0            |1.41         |9.0        |12.3        |
|2002-10-21 12:59:54 |2002-10-21 13:00:26  |2       |1.0            |0.0          |2.5        |5.8         |
|2002-10-21 12:38:08 |2002-10-21 12:38:28  |2       |1.0            |0.13         |2.5        |4.55        |
|2002-10-21 12:39:13 |2002-10-21 12:39:50  |2       |1.0            |0.27         |3.0        |5.05        |
|2002-10-21 12:58:14 |2002-10-21 12:58:22  |2       |1.0            |0.0          |65.0       |69.05       |
|2002-10-21 12:06:16 |2002-10-21 12:48:43  |2       |1.0            |22.92        |52.0       |63.1        |
|2002-10-21 12:53:50 |2002-10-21 12:56:15  |2       |1.0            |0.0          |52.0       |63.1        |
|2002-10-21 13:08:49 |2002-10-21 13:18:37  |2       |1.0            |1.46         |8.0        |13.56       |
|2002-10-21 14:59:29 |2022-06-06 15:22:37  |2       |1.0            |3.35         |16.5       |19.8        |
|2002-10-21 15:46:22 |2002-10-21 15:51:44  |2       |1.0            |1.35         |6.5        |9.8         |
|2002-10-21 15:58:33 |2002-10-21 16:09:04  |2       |1.0            |1.95         |9.0        |12.3        |
|2002-10-21 15:55:48 |2002-10-21 15:59:47  |2       |1.0            |0.99         |5.5        |8.8         |
|2002-10-21 16:19:19 |2002-10-21 16:25:46  |2       |1.0            |1.47         |7.0        |11.3        |
|2002-10-21 16:32:13 |2002-10-21 16:35:04  |2       |1.0            |0.77         |4.5        |10.56       |
|2002-10-21 16:35:43 |2022-06-06 16:44:29  |2       |1.0            |1.12         |8.0        |11.55       |
|2002-10-21 16:32:35 |2002-10-21 16:32:44  |2       |1.0            |0.0          |9.0        |14.75       |
|2002-10-21 16:34:18 |2022-06-06 17:07:01  |2       |1.0            |8.94         |29.5       |40.56       |
|2002-10-21 18:00:55 |2022-06-06 19:32:25  |2       |1.0            |62.55        |250.0      |260.3       |
|2002-10-21 19:06:11 |2022-06-06 19:31:55  |2       |3.0            |13.99        |55.0       |56.3        |
|2002-10-22 07:17:32 |2002-10-22 07:23:52  |2       |1.0            |1.1          |6.0        |9.3         |
|2002-10-22 08:28:35 |2002-10-22 08:28:43  |2       |2.0            |0.0          |62.0       |74.76       |
|2002-10-22 08:55:12 |2002-10-22 09:26:39  |2       |2.0            |3.86         |21.5       |24.8        |
|2002-10-22 09:09:36 |2002-10-22 09:09:43  |2       |3.0            |0.0          |40.0       |40.3        |
|2002-10-22 09:15:07 |2022-06-07 09:21:13  |2       |1.0            |1.03         |6.0        |9.3         |
|2002-10-22 09:11:17 |2002-10-22 09:41:46  |2       |1.0            |3.83         |20.0       |23.3        |
|2002-10-22 09:45:43 |2002-10-22 09:59:11  |2       |1.0            |1.3          |10.0       |15.96       |
+--------------------+---------------------+--------+---------------+-------------+-----------+------------+
only showing top 50 rows

In [ ]:
# ---------------------------------------------------------
# Define the intended analysis period
# January 2014 through May 2026
# ---------------------------------------------------------
START_DATE = "2014-01-01"
END_DATE = "2026-06-01"   # exclusive, so May 2026 is included

# ---------------------------------------------------------
# Count records that fall outside the intended period
# ---------------------------------------------------------
out_of_range_count = (
    df_cleaned
    .filter(
        (F.col("tpep_pickup_datetime") < F.lit(START_DATE)) |
        (F.col("tpep_pickup_datetime") >= F.lit(END_DATE))
    )
    .count()
)

print(f"Records outside analysis period: {out_of_range_count:,}")

# ---------------------------------------------------------
# Create filtered dataframe
# ---------------------------------------------------------
df_filtered = (
    df_cleaned
    .filter(
        (F.col("tpep_pickup_datetime") >= F.lit(START_DATE)) &
        (F.col("tpep_pickup_datetime") < F.lit(END_DATE))
    )
)

# ---------------------------------------------------------
# Check the resulting date range
# ---------------------------------------------------------
df_filtered.select(
    F.min("tpep_pickup_datetime").alias("earliest_pickup"),
    F.max("tpep_pickup_datetime").alias("latest_pickup")
).show(truncate=False)

# ---------------------------------------------------------
# Check row count after filtering
# ---------------------------------------------------------
filtered_count = df_filtered.count()

print(f"Rows after filtering: {filtered_count:,}")

Records outside analysis period: 2,712
+-------------------+-------------------+
|earliest_pickup    |latest_pickup      |
+-------------------+-------------------+
|2014-01-01 00:00:00|2026-05-31 23:59:59|
+-------------------+-------------------+

Rows after filtering: 985,997,389

Looking into negatives amounts

In [ ]:
df_filtered.filter(
    F.col("fare_amount") < 0
).select(
    "VendorID",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "payment_type",
    "congestion_surcharge",
    "airport_fee"
).show(50, truncate=False)

+--------+--------------------+---------------------+---------------+-------------+-----------+------+-------+----------+------------+---------------------+------------+------------+--------------------+-----------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|fare_amount|extra |mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|payment_type|congestion_surcharge|airport_fee|
+--------+--------------------+---------------------+---------------+-------------+-----------+------+-------+----------+------------+---------------------+------------+------------+--------------------+-----------+
|1       |2014-03-31 13:20:26 |2014-03-31 13:54:43  |1.0            |15.3         |-612.42    |628.37|30.05  |9.2       |0.0         |0.0                  |55.2        |1           |0.0                 |0.0        |
|2       |2014-08-01 00:14:19 |2014-08-01 00:17:33  |4.0            |0.39         |-4.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-5.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:28:35 |2014-08-01 00:30:00  |3.0            |0.51         |-3.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:56:13 |2014-08-01 00:59:17  |2.0            |0.99         |-5.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-6.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:16:59 |2014-08-01 00:24:42  |6.0            |0.67         |-6.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-7.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:42:22 |2014-08-01 00:43:00  |1.0            |0.3          |-3.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:28:30 |2014-08-01 00:30:44  |1.0            |0.03         |-3.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:31:41 |2014-08-01 00:31:45  |1.0            |0.0          |-7.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-8.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:54:01 |2014-08-01 00:54:27  |1.0            |0.07         |-52.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-52.5       |2           |0.0                 |0.0        |
|2       |2014-08-01 00:44:17 |2014-08-01 00:45:56  |1.0            |0.97         |-60.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-60.5       |2           |0.0                 |0.0        |
|2       |2014-08-01 00:44:58 |2014-08-01 00:46:52  |1.0            |0.13         |-3.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 00:15:04 |2014-08-01 00:15:06  |1.0            |0.05         |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 00:26:53 |2014-08-01 00:27:06  |3.0            |0.03         |-52.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-52.5       |3           |0.0                 |0.0        |
|2       |2014-08-01 00:35:56 |2014-08-01 00:37:33  |3.0            |0.33         |-3.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 01:51:56 |2014-08-01 01:51:59  |4.0            |0.0          |-52.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-52.5       |4           |0.0                 |0.0        |
|2       |2014-08-01 01:34:46 |2014-08-01 01:35:58  |1.0            |0.03         |-3.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 01:33:09 |2014-08-01 01:33:46  |6.0            |0.0          |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 01:55:38 |2014-08-01 01:57:02  |2.0            |0.69         |-4.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-5.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 01:54:25 |2014-08-01 02:02:09  |2.0            |0.34         |-5.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-6.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 01:26:07 |2014-08-01 01:26:13  |1.0            |0.0          |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 01:21:09 |2014-08-01 01:23:41  |1.0            |0.0          |-3.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 02:46:42 |2014-08-01 02:46:51  |1.0            |0.12         |-2.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 02:28:07 |2014-08-01 02:28:10  |2.0            |0.0          |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 02:53:34 |2014-08-01 02:53:35  |1.0            |0.14         |-3.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 02:25:47 |2014-08-01 02:27:05  |5.0            |0.08         |-3.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-4.0        |2           |0.0                 |0.0        |
|2       |2014-08-01 03:59:30 |2014-08-01 04:02:42  |1.0            |0.3          |-4.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-5.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 03:32:35 |2014-08-01 03:32:49  |1.0            |0.03         |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 03:03:26 |2014-08-01 03:36:10  |1.0            |0.94         |-15.0      |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-16.0       |4           |0.0                 |0.0        |
|2       |2014-08-01 04:00:44 |2014-08-01 04:08:34  |1.0            |0.07         |-6.0       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-7.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 05:53:06 |2014-08-01 05:53:11  |2.0            |0.02         |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 05:27:59 |2014-08-01 05:28:09  |1.0            |0.02         |-2.5       |-0.5  |-0.5   |0.0       |0.0         |0.0                  |-3.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 06:44:46 |2014-08-01 06:48:57  |1.0            |0.02         |-7.7       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-8.2        |2           |0.0                 |0.0        |
|2       |2014-08-01 06:57:57 |2014-08-01 07:00:19  |2.0            |0.03         |-12.5      |0.0   |0.0    |0.0       |0.0         |0.0                  |-12.5       |4           |0.0                 |0.0        |
|2       |2014-08-01 06:38:13 |2014-08-01 06:38:41  |4.0            |0.0          |-2.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 06:17:33 |2014-08-01 06:19:53  |2.0            |0.35         |-3.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-4.0        |4           |0.0                 |0.0        |
|2       |2014-08-01 06:37:09 |2014-08-01 06:37:10  |1.0            |0.39         |-10.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-10.5       |4           |0.0                 |0.0        |
|2       |2014-08-01 06:37:59 |2014-08-01 06:41:37  |1.0            |0.83         |-5.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-5.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 07:34:19 |2014-08-01 07:41:48  |2.0            |0.85         |-6.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-7.0        |2           |0.0                 |0.0        |
|2       |2014-08-01 07:54:14 |2014-08-01 07:54:17  |3.0            |0.01         |-52.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-52.5       |4           |0.0                 |0.0        |
|2       |2014-08-01 08:14:39 |2014-08-01 08:19:21  |1.0            |0.89         |-5.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-5.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 08:43:04 |2014-08-01 08:44:45  |1.0            |0.15         |-3.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 08:26:35 |2014-08-01 08:31:43  |5.0            |0.88         |-6.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-6.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 09:23:34 |2014-08-01 09:23:36  |1.0            |0.05         |-280.0     |0.0   |0.0    |-70.0     |0.0         |0.0                  |-350.0      |1           |0.0                 |0.0        |
|2       |2014-08-01 09:13:26 |2014-08-01 09:16:37  |3.0            |0.8          |-4.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-5.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 09:26:43 |2014-08-01 09:27:46  |5.0            |0.08         |-3.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 09:05:35 |2014-08-01 09:10:45  |2.0            |0.54         |-5.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-5.5        |4           |0.0                 |0.0        |
|2       |2014-08-01 09:07:35 |2014-08-01 09:07:37  |1.0            |0.66         |-52.0      |0.0   |-0.5   |0.0       |0.0         |0.0                  |-52.5       |2           |0.0                 |0.0        |
|2       |2014-08-01 09:13:00 |2014-08-01 09:14:23  |1.0            |0.0          |-3.0       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.5        |3           |0.0                 |0.0        |
|2       |2014-08-01 09:15:32 |2014-08-01 09:16:03  |1.0            |0.0          |-2.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.0        |3           |0.0                 |0.0        |
|2       |2014-08-01 09:17:55 |2014-08-01 09:18:26  |1.0            |0.0          |-2.5       |0.0   |-0.5   |0.0       |0.0         |0.0                  |-3.0        |3           |0.0                 |0.0        |
+--------+--------------------+---------------------+---------------+-------------+-----------+------+-------+----------+------------+---------------------+------------+------------+--------------------+-----------+
only showing top 50 rows

Checking the VendorId

In [ ]:
(
    df_filtered
    .groupBy("VendorID")
    .count()
    .orderBy("VendorID")
    .show(truncate=False)
)

+--------+---------+
|VendorID|count    |
+--------+---------+
|1       |397538641|
|2       |586617738|
|3       |10297    |
|4       |758881   |
|5       |1079     |
|6       |299866   |
|7       |770887   |
+--------+---------+

Checking the negative trip distance

In [ ]:
(
    df_filtered
    .filter(F.col("trip_distance") < 0)
    .select(
        "VendorID",
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "passenger_count",
        "trip_distance",
        "fare_amount",
        "total_amount",
        "payment_type"
    )
    .show(50, truncate=False)
)

+--------+--------------------+---------------------+---------------+-------------+-----------+------------+------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|fare_amount|total_amount|payment_type|
+--------+--------------------+---------------------+---------------+-------------+-----------+------------+------------+
|1       |2014-10-27 06:33:05 |2014-10-27 07:32:35  |1.0            |-3446729.6   |2.5        |13.16       |3           |
|1       |2015-02-05 07:02:26 |2015-02-05 07:02:29  |1.0            |-4.08401244E7|2.5        |3.8         |3           |
|1       |2015-02-07 15:56:13 |2015-02-07 15:57:03  |3.0            |-4.00955322E7|0.0        |1.3         |1           |
|1       |2015-04-24 08:27:04 |2015-04-24 08:29:40  |1.0            |-186318.4    |2.5        |3.3         |2           |
|2       |2019-11-20 16:51:31 |2019-11-20 17:51:56  |1.0            |-11.45       |39.59      |39.59       |2           |
|2       |2019-11-20 16:13:00 |2019-11-20 16:38:15  |1.0            |-4.69        |47.8       |48.6        |2           |
|2       |2019-11-20 17:06:09 |2019-11-20 18:37:19  |1.0            |-14.42       |50.16      |50.16       |1           |
|2       |2019-11-21 05:12:22 |2019-11-21 05:45:49  |1.0            |-8.55        |40.38      |46.5        |2           |
|2       |2019-11-21 14:32:08 |2019-11-21 14:34:45  |1.0            |-0.76        |10.5       |11.3        |2           |
|2       |2019-11-21 19:16:58 |2019-11-21 19:23:59  |1.0            |-1.17        |13.0       |13.8        |2           |
|2       |2019-11-21 21:09:29 |2019-11-21 21:55:25  |1.0            |-21.3        |49.7       |56.62       |2           |
|2       |2019-11-22 13:20:37 |2019-11-22 13:31:56  |1.0            |-0.77        |27.2       |28.0        |2           |
|2       |2019-11-22 13:06:21 |2019-11-22 13:56:19  |1.0            |-9.25        |58.68      |59.48       |2           |
|2       |2019-11-24 10:59:01 |2019-11-24 11:13:24  |1.0            |-0.07        |31.42      |31.42       |2           |
|2       |2019-11-25 06:32:39 |2019-11-25 06:43:57  |1.0            |-1.95        |14.01      |14.81       |2           |
|2       |2019-11-25 07:02:12 |2019-11-25 08:07:48  |1.0            |-14.69       |44.5       |45.3        |2           |
|2       |2019-11-25 08:06:00 |2019-11-25 08:53:50  |1.0            |-13.52       |36.74      |43.66       |2           |
|2       |2019-11-25 12:54:44 |2019-11-25 13:06:18  |1.0            |-1.74        |7.2        |8.0         |2           |
|2       |2019-11-25 14:08:51 |2019-11-25 14:51:37  |1.0            |-11.35       |31.37      |47.21       |2           |
|2       |2019-11-26 08:37:38 |2019-11-26 09:14:12  |1.0            |-3.59        |24.27      |25.07       |2           |
|2       |2019-11-26 09:13:15 |2019-11-26 09:22:04  |1.0            |-2.04        |7.34       |8.14        |2           |
|2       |2019-11-26 14:28:41 |2019-11-26 14:54:34  |1.0            |-4.03        |20.2       |37.49       |1           |
|2       |2019-11-26 15:55:45 |2019-11-26 17:07:49  |1.0            |-14.62       |41.92      |48.84       |2           |
|2       |2019-11-26 21:15:40 |2019-11-26 21:43:05  |1.0            |-4.31        |22.2       |32.55       |1           |
|2       |2019-11-26 23:01:50 |2019-11-26 23:25:08  |1.0            |-5.38        |25.2       |33.15       |1           |
|2       |2019-11-27 06:57:49 |2019-11-27 07:17:22  |1.0            |-6.01        |17.43      |18.23       |2           |
|2       |2019-11-27 13:21:31 |2019-11-27 14:19:39  |1.0            |-13.79       |52.2       |65.55       |1           |
|2       |2019-11-27 21:50:18 |2019-11-27 21:59:32  |1.0            |-1.49        |13.2       |21.75       |1           |
|2       |2019-11-28 15:27:57 |2019-11-28 15:40:22  |1.0            |-1.74        |13.2       |14.0        |2           |
|2       |2019-11-30 09:47:08 |2019-11-30 10:14:05  |1.0            |-14.31       |35.11      |41.23       |2           |
|2       |2019-11-30 16:28:03 |2019-11-30 16:39:46  |1.0            |-0.43        |8.0        |8.0         |2           |
|2       |2019-11-20 12:53:00 |2019-11-20 12:55:00  |1.0            |-0.19        |35.65      |39.2        |0           |
|2       |2019-11-20 12:59:00 |2019-11-20 13:44:00  |1.0            |-11.32       |23.77      |33.44       |0           |
|2       |2019-11-20 12:45:00 |2019-11-20 13:28:00  |1.0            |-12.9        |36.21      |39.76       |0           |
|2       |2019-11-20 12:51:00 |2019-11-20 13:20:00  |1.0            |-5.74        |27.46      |28.26       |0           |
|2       |2019-11-20 12:32:00 |2019-11-20 12:53:00  |1.0            |-7.93        |33.16      |36.71       |0           |
|2       |2019-11-20 12:43:00 |2019-11-20 14:08:00  |1.0            |-14.9        |36.21      |39.76       |0           |
|2       |2019-11-20 12:44:00 |2019-11-20 13:45:00  |1.0            |-12.97       |34.35      |37.9        |0           |
|2       |2019-11-20 12:20:00 |2019-11-20 12:38:00  |1.0            |-2.55        |13.42      |23.09       |0           |
|2       |2019-11-20 13:27:00 |2019-11-20 14:08:00  |1.0            |-0.13        |19.96      |22.71       |0           |
|2       |2019-11-20 13:24:00 |2019-11-20 14:16:00  |1.0            |-12.56       |40.18      |43.73       |0           |
|2       |2019-11-20 13:37:00 |2019-11-20 13:39:00  |1.0            |-0.49        |23.38      |26.93       |0           |
|2       |2019-11-20 13:20:00 |2019-11-20 13:44:00  |1.0            |-5.25        |17.56      |21.11       |0           |
|2       |2019-11-20 13:54:00 |2019-11-20 14:00:00  |1.0            |-0.37        |12.91      |16.46       |0           |
|2       |2019-11-20 13:02:00 |2019-11-20 14:09:00  |1.0            |-15.0        |45.09      |54.19       |0           |
|2       |2019-11-20 13:42:00 |2019-11-20 13:47:00  |1.0            |-1.06        |18.08      |21.63       |0           |
|2       |2019-11-20 13:59:00 |2019-11-20 14:19:00  |1.0            |-4.17        |18.08      |21.63       |0           |
|2       |2019-11-20 13:26:00 |2019-11-20 13:37:00  |1.0            |-13.34       |18.08      |21.63       |0           |
|2       |2019-11-20 13:20:00 |2019-11-20 14:10:00  |1.0            |-14.88       |47.91      |57.58       |0           |
|2       |2019-11-20 13:06:00 |2019-11-20 13:51:00  |1.0            |-13.5        |40.18      |43.73       |0           |
+--------+--------------------+---------------------+---------------+-------------+-----------+------------+------------+
only showing top 50 rows

In [ ]:
(
    df_standardised
    .filter(F.col("trip_distance") < 0)
    .withColumn("year", F.year("tpep_pickup_datetime"))
    .groupBy("year")
    .count()
    .orderBy("year")
    .show()
)

+----+-----+
|year|count|
+----+-----+
|2014|    1|
|2015|    3|
|2019| 9102|
|2020| 2338|
+----+-----+

In [ ]:
df_filtered_2 = df_filtered.filter(F.col("trip_distance") >= 0)

print("Remaining rows with negative distance:")
df_filtered_2.filter(F.col("trip_distance") < 0).count()

Remaining rows with negative distance:

0

In [ ]:
df_filtered_2.write \
    .mode("overwrite") \
    .parquet("/content/drive/MyDrive/MIT805/Group Project/ProcessedData/CleanedData")